source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'ReusableViewPool_Example', :exclusive => true do
  pod 'ReusableViewPool', :path => '../'
end

target 'ReusableViewPool_Tests', :exclusive => true do
  pod 'ReusableViewPool', :path => '../'

  
end
